apiVersion: v2
name: spark-on-k8s-chart
description: A Helm chart for Spark on Kubernetes with multi-tenant support, unified Volcano scheduling, and resource management

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"


dependencies:
  - name: spark-operator
    version: "2.0.2"
    repository: https://kubeflow.github.io/spark-operator
    condition: sparkOperator.enabled
    tags:
      - spark

  - name: volcano
    version: "1.10.0"
    repository: https://volcano-sh.github.io/helm-charts
    condition: volcano.enabled
    tags:
      - scheduler