# ==========================================
# Resource Quotas for All Teams
# ==========================================

# Default Scheduler Teams Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-beta-quota
  namespace: team-beta
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
---
# Volcano Scheduler Teams Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-theta-quota
  namespace: team-theta
spec:
  hard:
    requests.cpu: "6"
    requests.memory: "12Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "15"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-delta-quota
  namespace: team-delta
spec:
  hard:
    requests.cpu: "6"
    requests.memory: "12Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "15"
    persistentvolumeclaims: "5"
---
