{{- if .Values.global.createNamespaces }}
---
# Spark Operator Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
  labels:
    name: spark-operator
    {{- include "spark-on-k8s.labels" . | nindent 4 }}
  {{- with (include "spark-on-k8s.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}

{{- range .Values.teams }}
---
# Namespace for {{ .displayName }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- include "spark-on-k8s.team.labels" . | nindent 4 }}
    {{- include "spark-on-k8s.labels" $ | nindent 4 }}
  {{- with (include "spark-on-k8s.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
