{{- if .Values.global.createNamespaces }}
---
# Spark Operator Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
  labels:
    name: spark-operator
    {{- include "spark-on-k8s.labels" . | nindent 4 }}
  {{- with (include "spark-on-k8s.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}

{{- range .Values.teams.defaultScheduler }}
---
# Namespace for {{ .displayName }} (Default Scheduler)
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- include "spark-on-k8s.team.labels" . | nindent 4 }}
    {{- include "spark-on-k8s.labels" $ | nindent 4 }}
    scheduler: default
  {{- with (include "spark-on-k8s.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}

{{- range .Values.teams.volcanoScheduler }}
---
# Namespace for {{ .displayName }} (Volcano Scheduler)
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- include "spark-on-k8s.team.labels" . | nindent 4 }}
    {{- include "spark-on-k8s.labels" $ | nindent 4 }}
    scheduler: volcano
    {{- if .queue.name }}
    volcano-queue: {{ .queue.name }}
    {{- end }}
  {{- with (include "spark-on-k8s.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
